---
# This playbook defines the whole application stack.

# Apply common configuration to all hosts.
- hosts: localhost
  vars:
    tomcat_version: 8.5.23
    tomcat_users:
      - username: "tomcat"
        password: "yolo"
        roles: "tomcat,admin,manager,manager-gui"
      - username: "someuser"
        password: "1234"
        roles: "tomcat"
  roles:
    - tomcat
    - apache