---
# This playbook defines the whole application stack.

# Apply common configuration to all hosts.
- hosts: localhost
  become: true
  vars:
    tomcat_version: 8.5.23
    tomcat_users:
      - username: "tomcat"
        password: "yolo"
        roles: "tomcat,admin,manager,manager-gui"
  roles:
    - tomcat
    - apache